### PR TITLE
Correct CMake build rule (Fix #40)

### LINKED ISSUE #40: ROS buildfarm failure for 2dnav and bringup pkgs
ros-indigo-spur-2dnav: http://jenkins.ros.org/job/ros-indigo-spur-2dnav_binarydeb_trusty_amd64/2/
ros-indigo-spur-bringup: http://jenkins.ros.org/job/ros-indigo-spur-bringup_binarydeb_trusty_i386/2/

```
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
  Could not find a package configuration file provided by "urg_node" with any
  of the following names:

    urg_nodeConfig.cmake
    urg_node-config.cmake

  Add the installation prefix of "urg_node" to CMAKE_PREFIX_PATH or set
  "urg_node_DIR" to a directory containing one of the above files.  If
  "urg_node" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)
```
I think `urg_node` doesn't need to be `find_package`ed since it's a `run_depend` only.

### PR DESCRIPTION
**Pull request by 130s**
Don't know why locally neither `catkin build` nor `catkin_make` failed though.

### CODE REVIEW

**Comment by 130s** [comment]
And one way to automatically merge this PR is to revert https://github.com/tork-a/spur/pull/39#issuecomment-117991387 (as discussed in that thread).

**Comment by 130s** [comment]
@534o please let me know when I'm ready to rebase and merge this PR.

**Comment by 534o** [comment]
sorry for confusion, please rebase this, I think i have done everything I want to do for now.

on build firm, they compile each package, not entire repository, so if your package does not have correct depend, it fail to compile
On the other hand, on local machine we compile entire repository and run rosdep install for all packages in repository, so if there are dependency in other package in same repository, then we can compile them.

**Comment by 130s** [comment]
Other than travis failing [here](https://travis-ci.org/tork-a/spur/builds/69321302#L3684), which is handled in #46, the test result looks good. Let me go ahead merge.

```
Invalid roslaunch XML syntax: [Errno 2] No such file or directory: u'/home/travis/ros/ws_spur/src/spur/spur_controller/launch/spur_dynamixel.launch'
```

**Pull request merged**
