### PR TITLE
Add bringup, nav packages

### PR DESCRIPTION
**Pull request by 130s**
Mapping is enabled. 

However, setting 2D nav goal on RViz leads to these message and the robot won't start moving. Setting `2D Pose Estimate` seems not doing anything.
```
[ WARN] [1435660385.053779469, 2861.076000000]: The robot's start position is off the global costmap. Planning will always fail, are you sure the robot has been properly localized?
[ WARN] [1435660385.053804756, 2861.076000000]: The robot's start position is off the global costmap. Planning will always fail, are you sure the robot has been properly localized?
[ WARN] [1435660385.053840868, 2861.076000000]: The robot's start position is off the global costmap. Planning will always fail, are you sure the robot has been properly localized?
```

### CODE REVIEW

**Comment by 130s** [comment]
`2D nav goal` feature requires a map. At the time of this PR no sample map is provided in the spur package suite (but is planned to be included very soon), and localization isn't tested yet. So it's good to merge this PR.

**Comment by 534o** [comment]
No, it's not good to merge PR, at least travis said NO, please check travis log and fix your commit

**Comment by 534o** [comment]
````
[spur_bringup] ==> '/home/travis/ros/ws_spur/build/spur_bringup/build_env.sh /usr/bin/cmake /home/travis/ros/ws_spur/src/spur/spur_bringup -DCATKIN_DEVEL_PREFIX=/home/travis/ros/ws_spur/devel -DCMAKE_INSTALL_PREFIX=/home/travis/ros/ws_spur/install' in '/home/travis/ros/ws_spur/build/spur_bringup'

-- The C compiler identification is GNU

-- The CXX compiler identification is GNU

-- Check for working C compiler: /usr/bin/gcc

-- Check for working C compiler: /usr/bin/gcc -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Check for working CXX compiler: /usr/bin/g++

-- Check for working CXX compiler: /usr/bin/g++ -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Using CATKIN_DEVEL_PREFIX: /home/travis/ros/ws_spur/devel

-- Using CMAKE_PREFIX_PATH: /opt/ros/hydro

-- This workspace overlays: /opt/ros/hydro

-- Found PythonInterp: /usr/bin/python (found version "2.7.3")

-- Using PYTHON_EXECUTABLE: /usr/bin/python

-- Python version: 2.7

-- Using Debian Python package layout

-- Using CATKIN_ENABLE_TESTING: ON

-- Call enable_testing()

-- Using CATKIN_TEST_RESULTS_DIR: /home/travis/ros/ws_spur/build/spur_bringup/test_results

-- Looking for include files CMAKE_HAVE_PTHREAD_H

-- Looking for include files CMAKE_HAVE_PTHREAD_H - found

-- Looking for pthread_create in pthreads

-- Looking for pthread_create in pthreads - not found

-- Looking for pthread_create in pthread

-- Looking for pthread_create in pthread - found

-- Found Threads: TRUE 

-- Found gtest sources under '/usr/src/gtest': gtests will be built

-- catkin 0.5.90

CMake Error at /opt/ros/hydro/share/catkin/cmake/catkinConfig.cmake:75 (find_package):

  Could not find a configuration file for package spur_controller.

  Set spur_controller_DIR to the directory containing a CMake configuration

  file for spur_controller.  The file will have one of the following names:

    spur_controllerConfig.cmake

    spur_controller-config.cmake

Call Stack (most recent call first):

  CMakeLists.txt:7 (find_package)

-- Configuring incomplete, errors occurred!

[spur_bringup] <== '/home/travis/ros/ws_spur/build/spur_bringup/build_env.sh /usr/bin/cmake /home/travis/ros/ws_spur/src/spur/spur_bringup -DCATKIN_DEVEL_PREFIX=/home/travis/ros/ws_spur/devel -DCMAKE_INSTALL_PREFIX=/home/travis/ros/ws_spur/install' failed with return code '1'

                                                                                 

Failed   <== spur_bringup     [ 4.2 seconds ]                                   

Finished <== spur_2dnav       [ 4.6 seconds ]                                   

Finished <== spur_controller  [ 7.0 seconds ]                                   

]2;[build] There were '1' errors:                                                  

Failed to build package 'spur_bringup' because the following command:

# Command to reproduce:

cd /home/travis/ros/ws_spur/build/spur_bringup && /home/travis/ros/ws_spur/build/spur_bringup/build_env.sh /usr/bin/cmake /home/travis/ros/ws_spur/src/spur/spur_bringup -DCATKIN_DEVEL_PREFIX=/home/travis/ros/ws_spur/devel -DCMAKE_INSTALL_PREFIX=/home/travis/ros/ws_spur/install; cd -

# Path to log:

cat /home/travis/ros/ws_spur/build/build_logs/spur_bringup.log

Exited with return code: 1 
```

**Comment by 130s** [comment]
travis passed with my last change.

**Pull request merged**
